### ISSUE TITLE
工具有问题，工具就是单纯的解析url然后提取出url，并没有把url进行组合。而实际上如果要正确访问目标，需要将url进行组合才能访问。

### ISSUE THREAD

**Issue by Steady-brother** [dwisiswant0/wadl-dumper#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- wadl-dumper Version: 

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by dwisiswant0** [comment]
Use issue template wisely.
